INSERT INTO artists (name, genre_id) VALUES 
("AC/DC", 16), 
("Accept", 1), 
("Aerosmith",1), 
("Andre 3000",13), 
("Ariana Grande",13), 
("Beyoncé",14), 
("Black Eyed Peas",13), 
("Bobby Vinton", 18), 
("Boyz II Men",14), 
("Bruno Mars",13), 
("Carrie Underwood",14), 
("Celine Dion",13), 
("Cher",18), 
("Chris Brown",14), 
("Diana Ross",14), 
("Donna Summer",18), 
("Drake",15), 
("Elton John",18), 
("Eminem",1), 
("Fats Domino",18), 
("Four Tops",18), 
("Frank Sinatra",18), 
("Glee Cast",5), 
("Janet Jackson",14), 
("Jennifer Lopez",13), 
("Justin Timberlake",13), 
("Kanye West",15), 
("Katy Perry",13), 
("Kelly Clarkson",13), 
("Lady Gaga",13), 
("Lil Wayne",15), 
("Linda Ronstadt",12), 
("Ludacris",15), 
("Maroon 5",1), 
("Mary J. Blige",14), 
("Michael Jackson",14), 
("Nelly",14), 
("Nicki Minaj",15), 
("Pink",16), 
("Queen",16), 
("Rick Springfield",12), 
("Rihanna",14), 
("Shakira",11),
("Stevie Wonder",14), 
("T-Pain",14), 
("Taylor Swift",13), 
("The Beatles",18), 
("The Miracles",12), 
("Toni Braxton",14), 
("U2",1), 
("Usher",14);